# Generated by Django 2.2.7 on 2019-11-17 12:25

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(unique=True)),
                ('createdAt', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('updatedAt', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('dueDate', models.DateField(auto_now=True)),
                ('remindMeDate', models.DateField(default=None, null=True)),
                ('resolvedAt', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('title', models.TextField(max_length=146)),
                ('description', models.TextField(max_length=1024)),
                ('priority', models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, max_length=1)),
                ('status', models.CharField(choices=[(1, 'Open'), (2, 'In-progress'), (3, 'Resolved')], max_length=1)),
            ],
        ),
    ]
